AplicacionWeb/Models/Catalogo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AplicacionWeb.Models
{
    public class Catalogo
    {
        public string Titulo { get; set; }
        public string Id { get; set; }
        public string Precio { get; set; }
        public string Info { get; set; }




    }
}

AplicacionWeb/Controllers/HomeController.cs
using AplicacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace AplicacionWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult MiPerfil()
        {
            return View();
        }

        public ActionResult MailContacto()
        {

            return View();
        }

        public ActionResult Catalogo()
        {
            //QUE DISLEXIA, "manger", 10min de ver escrito manager
            ProductosManger manager = new ProductosManger();
            List<Productos> productos = manager.TodosProductos();
            ViewBag.Productos = productos;
            //se llama consultar todos para la lista

            return View();
        }


        //Almacenamiento de catalogo

        [HttpPost]
        public ActionResult Guardar(string nombre, string apellido, string email, string contraseña)
        {
            //Se guardan datos para lista de registrados y confirmacion por email.
            Models.Usuario usuarioNuevo = new Models.Usuario();

            usuarioNuevo.Nombre = nombre;
            usuarioNuevo.Apellido = apellido;
            usuarioNuevo.Email = email;
            usuarioNuevo.Contraseña = contraseña;

            List<Models.Usuario> lista = (List<Models.Usuario>)Session["usuarios"];

            if (lista == null)
            {
                lista = new List<Models.Usuario>();
            }


            lista.Add(usuarioNuevo);
            Session["usuarios"] = lista;

            //Envio de correo

            //Configuracion smtp
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 25;
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = true;
            //Correo electronico de la pagina


            string correoPag = "cristian.alarcon.tec@gmail.com";
            string contraseñaPag = "2210cristian22";
            smtp.Credentials = new NetworkCredential(correoPag, contraseñaPag);
            //Cuerpo de correo

            MailMessage EmailRegistro = new MailMessage();
            EmailRegistro.From = new MailAddress(correoPag);
            EmailRegistro.To.Add(email);
            EmailRegistro.IsBodyHtml = true;//VERIFICO COMANDO LUEGO
            EmailRegistro.Subject = "Confirmación de Cuenta ";
            EmailRegistro.Body = "Buen Día " + nombre + " " + apellido + " nos comunicamos para confirmar tu Email, recorda que al mismo llegaran las notificaciones de compra y otra información.";
            smtp.Send(EmailRegistro);





            return View();
        }

        //public ActionResult Modal(string Emailusuario, string Contraseñausuario)
        //{


        //}

        public ActionResult Logueo()
        {
            return View();

        }
 
       



    }

}

AplicacionWeb/Controllers/UsuarioAccionesController.cs
using AplicacionWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AplicacionWeb.Controllers
{
    public class UsuarioAccionesController : Controller
    {
        [HttpPost]

        public ActionResult LogueoUsuario(string email, string contraseña)
        {
            UsuarioManager manager = new UsuarioManager();
            Usuario usuario = manager.validar(email, contraseña);
            if (usuario!=null)
            {
                Session["UsuarioLogueado"] = usuario;

                TempData["Ingresaste Correctamente"] = "Espera un Segundo";
            }

            else
            {
                TempData["Error al Conectarse"] = "El usuario no existe o los datos no son correctos";
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult CerrarSesion()
        {
            Session["UsuarioLogueado"] = null;
            return RedirectToAction("Index", "Home");
        }

    }
}

AplicacionWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AplicacionWeb/Views/Home/Catalogo.cshtml
@{
    ViewBag.Title = "Catalogo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="novedades" >
    <!--Comienzo Columnas-->
    <h1>Catálogo</h1>
    <div id="articulos"><!--sql productos-->
        @if (ViewBag.Productos != null)
        {
            foreach (AplicacionWeb.Models.Productos producto in ViewBag.Productos)
            {

                <div class="row featurette">
                    <!--verificar datos-->
                    <div class="col-md-8 col-md-push-4">
                        <h2 class="featurette-heading">@producto.Titulo <span class="text-muted">Compralo ahora por $@producto.Precio</span></h2>
                        <p class="lead">
                            @producto.Info
                        </p>
                        <br>
                        <button class="btn btn-default" type="button"><a href="#">Comprar</a></button>
                        <button class="btn btn-block" type="button"> <a href=@Url.Action("compraCatalogo", "Home")></a>Agregar a Compras</button>
                    </div>
                    <br>
                    <div class="col-md-4 col-md-pull-8">
                        <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="@producto.Imagen" data-holder-rendered="true">
                    </div>
                </div>

                <hr class="featurette-divider">

                <!--Verificacion de row al otro lado-->

                <div class="row featurette">
                    <div class="col-md-8 col-md-push-4">
                        <h2 class="featurette-heading">@producto.Titulo <span class="text-muted">Compralo ahora por $.</span></h2>
                        <p class="lead">@producto.Info
                        </p>

                        <br>
                        <button class="btn btn-default" type="button"><a href="#">Comprar</a></button>
                    <button class="btn btn-block" type="button">Agregar a Compras</button>
                    </div>
                    <br>
                    <div class="col-md-4 col-md-pull-8">
                        <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="@producto.Imagen" data-holder-rendered="true">
                    </div>
                </div>
                <hr class="featurette-divider">


                <!--fin verificacion-->
            }
        }
    </div><!--fin sql productos-->

    @*<hr class="featurette-divider">
    <div class="row featurette">
        <!--verificar datos-->
        <div class="col-md-8">
            <h2 class="featurette-heading">The Walking Dead: A New Frontier <span class="text-muted">Compralo ahora por $.</span></h2>
            <p class="lead">
                Mientras Javier, un joven decidido a encontrar a la familia que le quitaron, tú conoces a una joven que ha experimentado su propia e inimaginable pérdida. Su nombre es Clementine,
                y sus destinos están unidos en una historia en la que cada elección que hagan puede ser la última
            </p>
            <br>
            <button class="btn btn-success" type="button">Comprar</button>
            <button class="btn btn-primary" type="button" value="The Walking Dead: A New Frontier"> <a href=@Url.Action("compraCatalogo","Home")></a>Agregar a Compras</button>
        </div>
        <br>
        <div class="col-md-4">
            <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1YTkxZDdiZDI3IHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTVhOTFkN2JkMjciPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-8 col-md-push-4">
            <h2 class="featurette-heading">Mad Max <span class="text-muted">Compralo ahora por $.</span></h2>
            <p class="lead">
                Conviértete en Mad Max, un guerrero solitario en un despiadado mundo postapocalíptico donde los vehículos son imprescindibles para la supervivencia.
                En este juego de acción de mundo abierto en tercera persona deberás luchar constantemente contra crueles enemigos para mantenerte con vida en el Páramo.
            </p>

            <br>
            <button class="btn btn-success" type="button">Comprar</button>
            <button class="btn btn-primary" type="button">Agregar a Compras</button>

        </div>
        <br>
        <div class="col-md-4 col-md-pull-8">
            <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1YTkxZDgxYWEzIHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTVhOTFkODFhYTMiPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
    </div>
    <hr class="featurette-divider">
    <!--Punto-->
    <div class="row featurette">
        <div class="col-md-8">
            <h2 class="featurette-heading">Dark Souls III <span class="text-muted">Compralo ahora por $.</span></h2>
            <p class="lead">
                Conviértete en Mad Max, un guerrero solitario en un despiadado mundo postapocalíptico donde los vehículos son imprescindibles para la supervivencia.
                En este juego de acción de mundo abierto en tercera persona deberás luchar constantemente contra crueles enemigos para mantenerte con vida en el Páramo.
            </p>
            <br>
            <button class="btn btn-success" type="button">Comprar</button>
            <button class="btn btn-primary" type="button">Agregar a Compras</button>

        </div>
        <br>
        <div class="col-md-4">
            <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1YTkxZDdlZjdhIHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTVhOTFkN2VmN2EiPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
    </div>
    <!--Punto-->
    
   
    <!--Punto-->
    
    <!--Punto-->
    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-8 col-md-push-4">
            <h2 class="featurette-heading">Mad Max <span class="text-muted">Compralo ahora por $.</span></h2>
            <p class="lead">
                Conviértete en Mad Max, un guerrero solitario en un despiadado mundo postapocalíptico donde los vehículos son imprescindibles para la supervivencia.
                En este juego de acción de mundo abierto en tercera persona deberás luchar constantemente contra crueles enemigos para mantenerte con vida en el Páramo.
            </p>

            <br>
            <button class="btn btn-success" type="button">Comprar</button>
            <button class="btn btn-primary" type="button">Agregar a Compras</button>

        </div>
        <br>
        <div class="col-md-4 col-md-pull-8">
            <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1YTkxZDgxYWEzIHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTVhOTFkODFhYTMiPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4=" data-holder-rendered="true">
        </div>
    </div>
    <hr class="featurette-divider">*@
    <!--Nav de pagina-->
    <nav aria-label="pagination pagination-lg">
        <ul class="pager">
            <li><a href="">Anterior</a></li>
            <li><a href="">Siguiente</a></li>
        </ul>
    </nav>
    <!--Nav-->





</div><!--Fin columnas-->

AplicacionWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AplicacionWeb/Views/Home/Guardar.cshtml
@{
    ViewBag.Title = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Confirmación de Registro</h2>
<div class="row">
    <div class="col-md-4">
        <div class="alert-info">Te has registrado correctamente, verifica tu bandeja de entrada para confirmar el Email.</div>


    </div>

</div>

AplicacionWeb/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br>
<div class="container" id="login"><!--Login-->
    <h2 class="text-center">Registrate</h2>
    <hr class="featurette-divider">
    <br>
    <form action="@Url.Action("login","UsuarioAcciones")" method="post" class="form-horizontal">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Nombre</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="nombre" placeholder="Tu Nombre" width="60">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">Apellido</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="apellido" placeholder="Tu Apellido" width="60">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">Email</label>
            <div class="col-sm-4">
                <input type="email" class="form-control" name="email" placeholder="Tu Correo" width="60">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">Contraseña</label>
            <div class="col-sm-4">
                <input type="password" class="form-control" name="contraseña" placeholder="Tu Contraseña" maxlength="8" width="60">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Recuerdame
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success" value="Guardar">Registrate</button>
            </div>
        </div>
    </form>
</div>
<!--Fin div de login-->

AplicacionWeb/Views/Home/Logueo.cshtml
@{
    ViewBag.Title = "Logueo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="logueo">
    <h2 class="text-center">Ingresa con tu Usuario</h2>
    <hr class="featurette-divider">
    <br>
    <form action="@Url.Action("LogueoUsuario", "UsuarioAcciones")" method="post" class="form-horizontal">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-4 control-label">Email</label>
            <div class="col-sm-4">
                <input type="email" class="form-control" name="email" placeholder="Tu Correo" width="120">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-4 control-label">Contraseña</label>
            <div class="col-sm-4">
                <input type="password" class="form-control" name="contraseña" placeholder="Tu Contraseña" maxlength="8" width="120">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Recuerdame
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <button type="submit" class="btn btn-success" value="Guardar">Inicia Sesión</button>
            </div>
        </div>


    </form>








    @*<form action="@Url.Action("LogueoUsuario", "UsuarioAcciones")" method="post" class="form-signin">
        <h2 class="form-signin-heading">Por favor ingresá</h2>
        <label for="inputEmail" class="sr-only">Email</label>
        <input type="email" name="email" class="form-control" placeholder="" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="contraseña" class="form-control" placeholder="" required="">

        <button class="btn btn-lg btn-primary btn-block" type="submit">Ingresar</button>
    </form>*@





</div>

AplicacionWeb/Views/Home/MailContacto.cshtml
@{
    ViewBag.Title = "MailContacto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container ">
    <form action="/Registro/Guardar" method="post">


        <div class="row">
            <label class="col-md-2 aladerecha">Nombre</label>
            <input class="col-md-4" type="text" name="nombre" />
        </div>
        <div class="row">
            <label class="col-md-2 aladerecha">Correo</label>
            <input class="col-md-4" type="number" name="mail" />
        </div>
        <div class="row">
            <label class="col-md-2 aladerecha">Correo</label>
            <input class="col-md-4" type="number" name="mensaje" />
        </div>
        <div class="row">
            <div class="col-md-6 aladerecha">
                <input class="btn-default" type="submit" value="Enviar" />
            </div>
        </div>
    </form>
</div>

AplicacionWeb/Views/Home/MiPerfil.cshtml
@{
    ViewBag.Title = "MiPerfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="tab-pane">
    <!--Comienzo de tab-->
    <h2>Mi Perfil</h2>
    <ul id="tabperfil" class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="active"><a href="#Perfil" id="Perfiltab" data-toggle="tab" role="tab">Mi Perfil</a></li>
        <li role="presentation"><a href="#Compras" id="Comprastab" data-toggle="tab" role="tab">Mis Compras</a></li>
        <li role="presentation"><a href="#Datos" id="Datostab" data-toggle="tab" role="tab">Configuracion</a></li>
    </ul>
</div><!--Fin de tab-->
<!--Se colocaron id para verificar luego la actualizacion de datos-->
<!--Info de tab-->
<div class="tab-content">
    <div id="Perfil" class="tab-pane fade" aria-labelledby="profile-tab">
        Contenido tab1
    </div>
    <div id="Compras" class="tab-pane fade" aria-labelledby="profile-tab">
        Contenido tab2
    </div>
    <div id="Datos" class="tab-pane fade" aria-labelledby="profile-tab">
        Contenido tab3
    </div>
</div>